spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1342b3674a3846b5cf45
            client-secret: d1643a0f484bf6bf005ccea70390f68aebe35dd9